### ISSUE TITLE
Can't install rexml/document

### ISSUE THREAD

**Issue by f00d4w0rm4** [digininja/CeWL#76]
Hello!  I can't get cewl to run because I can't install rexml/document.  I installed rexml.  Any advice??

```
╭─f00d4w0rm5@Garuda in ~ took 1s
╰─λ cewl --help
CeWL 5.5.1 (Grouping) Robin Wood (robin@digi.ninja) (https://digi.ninja/)

Error: rexml/document gem not installed
use: "gem install rexml/document" to install the required gem


╭─f00d4w0rm5@Garuda in ~ took 685ms
╰─λ gem install rexml/document
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
bad response Not Found 404 (https://index.rubygems.org/info/rexml/document)
```

**Comment by digininja** [comment]
Install bundler and then use that to install all the dependencies.

```
gem install bundler

bundle install
```

**Comment by f00d4w0rm4** [comment]
Thanks for your quick response!  I'm getting a new error now, here's what I did:

```
╭─f00d4w0rm5@Garuda in repo: CeWL🔒 on  master via  v3.0.1 took 1ms
╰─λ gem install bundler
Fetching bundler-2.2.18.gem
WARNING:  You don't have /home/f00d4w0rm5/.local/share/gem/ruby/3.0.0/bin in your PATH,
gem executables will not run.
Successfully installed bundler-2.2.18
1 gem installed

╭─f00d4w0rm5@Garuda in repo: CeWL🔒 on  master via  v3.0.1 took 2s
╰─λ bundle install
/usr/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /home/f00d4w0rm5/Documents/Hacking/tools/wordlists/CeWL/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
from /usr/lib/ruby/3.0.0/rubygems.rb:300:in `activate_bin_path'
from /usr/bin/bundle:23:in `<main>'

╭─f00d4w0rm5@Garuda in repo: CeWL🔒 on  master via  v3.0.1 took 1s
[🔴] × sudo bundle update --bundler
Using bundler 2.2.18
Using mime 0.4.4
Using mime-types-data 3.2019.0331
Using mime-types 3.2.2
Using mini_exiftool 2.9.0
Using mini_portile2 2.5.1
Using racc 1.5.2
Using nokogiri 1.11.4 (x86_64-linux)
Using spider 0.5.3
Using zip 2.0.2
Warning: the lockfile is being updated to Bundler 2, after which you will be unable to return to Bundler 1.
Bundle updated!

╭─f00d4w0rm5@Garuda in repo: CeWL🔒 on  master [!] via  v3.0.1 took 1s
╰─λ bundle install
Using bundler 2.2.18
Using mime 0.4.4
Following files may not be writable, so sudo is needed:
/usr/bin
/usr/lib/ruby/gems/3.0.0
/usr/lib/ruby/gems/3.0.0/build_info
/usr/lib/ruby/gems/3.0.0/cache
/usr/lib/ruby/gems/3.0.0/doc
/usr/lib/ruby/gems/3.0.0/extensions
/usr/lib/ruby/gems/3.0.0/gems
/usr/lib/ruby/gems/3.0.0/plugins
/usr/lib/ruby/gems/3.0.0/specifications
Using mime-types-data 3.2019.0331
Using mime-types 3.2.2
Using mini_exiftool 2.9.0
Using mini_portile2 2.5.1
Using racc 1.5.2
Using nokogiri 1.11.4 (x86_64-linux)
Using spider 0.5.3
Using zip 2.0.2
Bundle complete! 6 Gemfile dependencies, 10 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

╭─f00d4w0rm5@Garuda in repo: CeWL🔒 on  master [!] via  v3.0.1 took 1s
╰─λ ./cewl.rb --help
CeWL 5.5.1 (Grouping) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _1 is reserved for numbered parameter (SyntaxError)
/usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _2 is reserved for numbered parameter
/usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _3 is reserved for numbered parameter
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types.rb:228:in `<top (required)>'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime-types.rb:3:in `<top (required)>'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
from /home/f00d4w0rm5/Documents/Hacking/tools/wordlists/CeWL/cewl_lib.rb:13:in `<top (required)>'
from ./cewl.rb:43:in `require_relative'
from ./cewl.rb:43:in `<main>'
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- mime-types (LoadError)
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /home/f00d4w0rm5/Documents/Hacking/tools/wordlists/CeWL/cewl_lib.rb:13:in `<top (required)>'
from ./cewl.rb:43:in `require_relative'
from ./cewl.rb:43:in `<main>'
```

**Comment by digininja** [comment]
The second to last command looks like it is failing as it can't access some
files, try running it with sudo as it suggests.

The warnings at the start of running are known about and are a problem with
a dependency but don't affect things.

**Comment by f00d4w0rm4** [comment]
Oh sorry, I tried that originally, copied the wrong one.  I tried it again anyways, still no luck.  I'm running these commands from within the cewl folder I git cloned.  I also tried installing it with pacman from the blackarch repo and did the same steps in the /usr/share/cewl folder, it has the original error:

```
╭─f00d4w0rm5@Garuda in /usr/share/cewl🔒 via  v3.0.1 took 1s
╰─λ cewl
CeWL 5.5.1 (Grouping) Robin Wood (robin@digi.ninja) (https://digi.ninja/)

Error: rexml/document gem not installed
use: "gem install rexml/document" to install the required gem
```

The error from the git folder looks to be the same as before:
```
╭─f00d4w0rm5@Garuda in repo: CeWL🔒 on  master [!] via  v3.0.1 took 2s
╰─λ ./cewl.rb --help
CeWL 5.5.1 (Grouping) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _1 is reserved for numbered parameter (SyntaxError)
/usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _2 is reserved for numbered parameter
/usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _3 is reserved for numbered parameter
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime/types.rb:228:in `<top (required)>'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /usr/lib/ruby/gems/3.0.0/gems/mime-types-3.2.2/lib/mime-types.rb:3:in `<top (required)>'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
from /home/f00d4w0rm5/Documents/Hacking/tools/wordlists/CeWL/cewl_lib.rb:13:in `<top (required)>'
from ./cewl.rb:43:in `require_relative'
from ./cewl.rb:43:in `<main>'
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- mime-types (LoadError)
from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /home/f00d4w0rm5/Documents/Hacking/tools/wordlists/CeWL/cewl_lib.rb:13:in `<top (required)>'
from ./cewl.rb:43:in `require_relative'
from ./cewl.rb:43:in `<main>'
```

**Comment by digininja** [comment]
Ok, I think I know that this is, I think it is related to an open issue
where one of the gem names is wrong or has changed.

I'll have a look, but try installing mime-types and see if that fixes it.

**Comment by digininja** [comment]
Glad it is sorted.

There is a bug with the Gemfile that I'll try to workout how to fix, glad
it is all working for you now.

**Comment by digininja** [comment]
It was a version issue with mime-types. The earlier versions had a bug with a constructor which used to be considered a warning but is now a syntax error so stops things from working. I've just update the Gemfile to force a minimum version which doesn't have the bug. 'bundle install` will now work.
